#!/usr/bin/env python3
"""Capture Home OS Migration P1 PR screenshots (~1440px)."""

from __future__ import annotations

import os
import sys
import threading
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "pr-screenshots" / "home-os-migration-p1"
DB = ROOT / ".tmp-home-os-migration-p1-screenshots.db"
PORT = 8877


def main() -> int:
    sys.path.insert(0, str(ROOT))
    os.environ["SECRET_KEY"] = "home-os-migration-p1-screenshot-secret"
    os.environ["DEMO_MODE"] = "true"
    os.environ["HOME_OS_ENABLED"] = "true"
    os.environ["RAILWAY_ENVIRONMENT_NAME"] = "staging"
    os.environ["RAILWAY_ENVIRONMENT"] = "staging"
    os.environ.pop("MIGHTY_ENV", None)
    os.environ["DATABASE_PATH"] = str(DB)
    if DB.exists():
        DB.unlink()

    import app as mighty
    from werkzeug.serving import make_server

    mighty.DATABASE = str(DB)
    with mighty.app.app_context():
        mighty.init_db()

    OUT.mkdir(parents=True, exist_ok=True)
    server = make_server("127.0.0.1", PORT, mighty.app, threaded=True)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    time.sleep(0.4)

    from playwright.sync_api import sync_playwright

    base = f"http://127.0.0.1:{PORT}"
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch()
            context = browser.new_context(
                viewport={"width": 1440, "height": 1100},
                device_scale_factor=2,
            )
            page = context.new_page()

            # Attention — default research entry now lands on Home OS
            page.goto(f"{base}/research/home", wait_until="networkidle")
            page.wait_for_selector('[data-home-os="1"]')
            page.screenshot(path=str(OUT / "attention.png"), full_page=False)

            # Opportunity slot — repair interaction (migration has no Opportunity type yet)
            page.locator("button.home-os__primary").click()
            page.wait_for_selector("#home-os-repair-root:not([hidden])")
            page.screenshot(path=str(OUT / "opportunity.png"), full_page=False)

            # All-clear after staged repair
            page.get_by_role("button", name="Confirm sign-in").click()
            page.wait_for_selector('[data-repair-phase="succeeded"]')
            page.screenshot(path=str(OUT / "all-clear.png"), full_page=False)

            browser.close()
    finally:
        server.shutdown()

    (OUT / "README.md").write_text(
        """# Home OS Migration P1 — PR screenshots

Staging default landing is Home OS when `HOME_OS_ENABLED=true`.

**Do not embed these images in chat.** Open files from the repository.

| File | What it shows |
|------|----------------|
| `attention.png` | Default staging Home OS with Marriott Interrupt (via `/research/home`) |
| `opportunity.png` | In-place repair modal (interaction; Opportunity Work Items not yet migrated) |
| `all-clear.png` | Calm Home after staged repair + Proof |

Generated by `scripts/capture_home_os_migration_p1_screenshots.py`.
""",
        encoding="utf-8",
    )
    print(f"Wrote screenshots to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
