#!/usr/bin/env python3
"""Capture Home OS Future Preview PR screenshots (~1440px)."""

from __future__ import annotations

import os
import sys
import threading
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "pr-screenshots" / "home-os-future-preview"
DB = ROOT / ".tmp-home-os-future-preview-screenshots.db"
PORT = 8878


def main() -> int:
    sys.path.insert(0, str(ROOT))
    os.environ["SECRET_KEY"] = "home-os-future-preview-screenshot-secret"
    os.environ["DEMO_MODE"] = "true"
    os.environ["HOME_OS_ENABLED"] = "true"
    os.environ["RAILWAY_ENVIRONMENT_NAME"] = "staging"
    os.environ["RAILWAY_ENVIRONMENT"] = "staging"
    os.environ.pop("MIGHTY_ENV", None)
    os.environ["DATABASE_PATH"] = str(DB)
    if DB.exists():
        DB.unlink()

    import app as mighty
    from werkzeug.serving import make_server

    mighty.DATABASE = str(DB)
    with mighty.app.app_context():
        mighty.init_db()

    OUT.mkdir(parents=True, exist_ok=True)
    server = make_server("127.0.0.1", PORT, mighty.app, threaded=True)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    time.sleep(0.4)

    from playwright.sync_api import sync_playwright

    base = f"http://127.0.0.1:{PORT}"
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch()
            context = browser.new_context(
                viewport={"width": 1440, "height": 1100},
                device_scale_factor=2,
            )
            page = context.new_page()

            # Attention — Approval ranked first
            page.goto(
                f"{base}/research/home-os/future?state=attention",
                wait_until="networkidle",
            )
            page.wait_for_selector('[data-home-os="1"]')
            page.screenshot(path=str(OUT / "attention.png"), full_page=False)

            # Opportunity — Opportunities only
            page.goto(
                f"{base}/research/home-os/future?state=opportunity",
                wait_until="networkidle",
            )
            page.wait_for_selector('[data-home-os="1"]')
            page.screenshot(path=str(OUT / "opportunity.png"), full_page=False)

            # All-clear — calm household with Coverage + Proof
            page.goto(
                f"{base}/research/home-os/future?state=all-clear",
                wait_until="networkidle",
            )
            page.wait_for_selector('[data-home-os="1"]')
            page.screenshot(path=str(OUT / "all-clear.png"), full_page=False)

            browser.close()
    finally:
        server.shutdown()

    (OUT / "README.md").write_text(
        """# Home OS Future Preview — PR screenshots

Deterministic review-only scenario at `/research/home-os/future`.

**Do not embed these images in chat.** Open files from the repository.

| File | What it shows |
|------|----------------|
| `attention.png` | Approval (United award) ranked first — needs user |
| `opportunity.png` | Opportunities only — value waiting (Chase transfer bonus) |
| `all-clear.png` | Calm Home with full Coverage + historical Proof |

Generated by `scripts/capture_home_os_future_preview_screenshots.py`.
""",
        encoding="utf-8",
    )
    print(f"Wrote screenshots to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
